<?php
/**
 * generate_pdf.php
 * -------------------------------------------------------------
 * Builds a PDF summary of the prescription exam + AI clinical
 * analysis, and saves it automatically to /pdf_file/{exam_code}.pdf
 *
 * REQUIRES: the FPDF library (single file, no dependencies).
 *   1. Download it from: http://www.fpdf.org/en/dl.php?v=189
 *   2. Extract "fpdf.php" into a folder named "fpdf" in the project
 *      root, so the path is: fpdf/fpdf.php
 * -------------------------------------------------------------
 */

session_start();
header('Content-Type: application/json');

include 'db_config.php';
include 'config_helper.php';

if (!isset($_SESSION['user_id'])) {
    http_response_code(401);
    echo json_encode(['error' => 'Unauthorized. Please log in again.']);
    exit();
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['error' => 'Method not allowed. Use POST.']);
    exit();
}

$fpdf_path = __DIR__ . '/fpdf/fpdf.php';
if (!file_exists($fpdf_path)) {
    http_response_code(500);
    echo json_encode([
        'error' => 'PDF library not found.',
        'hint'  => 'Download fpdf.php from http://www.fpdf.org/en/dl.php?v=189 and place it at fpdf/fpdf.php in the project root.'
    ]);
    exit();
}
require_once $fpdf_path;

$raw = file_get_contents('php://input');
$input = json_decode($raw, true);
if (!is_array($input) || empty($input['exam_code'])) {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid payload: exam_code is required.']);
    exit();
}

$exam_code = trim($input['exam_code']);
$patient   = $input['patient']  ?? [];
$new_rx    = $input['new_prescription'] ?? [];
$old_rx    = $input['old_prescription'] ?? null;
$analysis  = $input['analysis'] ?? [];

// Filename: exam code often contains "/" (e.g. LZ/EC/001/VII/2026), which is
// not valid in a filename, so it is replaced with "-".
$safe_filename = preg_replace('/[\/\\\\:*?"<>|]+/', '-', $exam_code) . '.pdf';

$output_dir = __DIR__ . '/pdf_file';
if (!is_dir($output_dir)) {
    mkdir($output_dir, 0755, true);
}
$output_path = $output_dir . '/' . $safe_filename;

// ---------------------------------------------------------------
// Small helper: FPDF's core fonts only support Latin-1, so UTF-8
// text coming from the AI (Bahasa Indonesia) must be converted.
// ---------------------------------------------------------------
function pdfText($str) {
    return iconv('UTF-8', 'ISO-8859-1//TRANSLIT', (string)$str);
}

class PrescriptionPDF extends FPDF {
    function Header() {
        $this->SetFont('Arial', 'B', 14);
        $this->Cell(0, 8, pdfText('Optical Prescription & AI Clinical Analysis'), 0, 1, 'C');
        $this->SetFont('Arial', '', 9);
        $this->SetTextColor(120, 120, 120);
        $this->Cell(0, 5, pdfText('Generated by Google Gemini AI - for optometrist reference only'), 0, 1, 'C');
        $this->SetTextColor(0, 0, 0);
        $this->Ln(3);
    }

    function SectionTitle($title) {
        $this->SetFont('Arial', 'B', 11);
        $this->SetFillColor(230, 230, 230);
        $this->Cell(0, 7, pdfText($title), 0, 1, 'L', true);
        $this->SetFont('Arial', '', 10);
        $this->Ln(1);
    }

    function BodyText($text) {
        $this->SetFont('Arial', '', 10);
        $this->MultiCell(0, 5.5, pdfText($text));
        $this->Ln(1);
    }

    function BulletList($items) {
        $this->SetFont('Arial', '', 10);
        foreach ($items as $item) {
            $this->MultiCell(0, 5.5, pdfText('- ' . $item));
        }
        $this->Ln(1);
    }
}

$pdf = new PrescriptionPDF();
$pdf->AliasNbPages();
$pdf->AddPage();

// ---- PATIENT & EXAM INFO ----
$pdf->SectionTitle('Patient & Examination Info');
$pdf->BodyText('Examination Code: ' . $exam_code);
$pdf->BodyText('Name: ' . ($patient['name'] ?? '-') . '   |   Gender: ' . ($patient['gender'] ?? '-') . '   |   Age: ' . ($patient['age'] ?? '-'));

// ---- REFERRAL ALERT (if recommended) ----
$referral = $analysis['referral'] ?? null;
if (!empty($referral['recommended'])) {
    $pdf->SetFillColor(255, 220, 220);
    $pdf->SetTextColor(180, 0, 0);
    $pdf->SetFont('Arial', 'B', 11);
    $pdf->MultiCell(0, 7, pdfText('!! REFERRAL TO SPECIALIST RECOMMENDED: ' . ($referral['specialist'] ?? '')), 0, 'L', true);
    $pdf->SetFont('Arial', '', 10);
    $pdf->MultiCell(0, 5.5, pdfText($referral['reason'] ?? ''), 0, 'L', true);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->Ln(2);
}

// ---- PRESCRIPTIONS ----
function rxLine($label, $rx) {
    if (!is_array($rx)) return $label . ': -';
    return sprintf(
        '%s | RIGHT (OD): SPH %s CYL %s AXIS %s ADD %s | LEFT (OS): SPH %s CYL %s AXIS %s ADD %s',
        $label,
        $rx['r_sph'] ?? '0.00', $rx['r_cyl'] ?? '0.00', $rx['r_ax'] ?? '0', $rx['r_add'] ?? '0.00',
        $rx['l_sph'] ?? '0.00', $rx['l_cyl'] ?? '0.00', $rx['l_ax'] ?? '0', $rx['l_add'] ?? '0.00'
    );
}
$pdf->SectionTitle('Prescription');
$pdf->BodyText(rxLine('New', $new_rx));
if ($old_rx) {
    $pdf->BodyText(rxLine('Previous', $old_rx));
}

// ---- MAIN FINDINGS ----
if (!empty($analysis['main_findings']) && is_array($analysis['main_findings'])) {
    $pdf->SectionTitle('Possible Conditions, Causes & Management');
    foreach ($analysis['main_findings'] as $f) {
        $pdf->SetFont('Arial', 'B', 10);
        $pdf->MultiCell(0, 5.5, pdfText(($f['name'] ?? '-') . ' (' . ($f['severity'] ?? '-') . ')'));
        if (!empty($f['explanation'])) $pdf->BodyText($f['explanation']);
        if (!empty($f['causes'])) { $pdf->SetFont('Arial','B',9); $pdf->Cell(0,5,pdfText('Causes:'),0,1); $pdf->BulletList($f['causes']); }
        if (!empty($f['management'])) { $pdf->SetFont('Arial','B',9); $pdf->Cell(0,5,pdfText('Management:'),0,1); $pdf->BulletList($f['management']); }
    }
}

// ---- PER-EYE ANALYSIS ----
foreach ([['right_eye', 'Right Eye (OD)'], ['left_eye', 'Left Eye (OS)']] as [$key, $label]) {
    $eye = $analysis[$key] ?? null;
    if (!$eye) continue;
    $pdf->SectionTitle($label);
    if (!empty($eye['summary'])) $pdf->BodyText($eye['summary']);
    foreach (($eye['conditions'] ?? []) as $c) {
        $pdf->SetFont('Arial', 'B', 10);
        $pdf->MultiCell(0, 5.5, pdfText(($c['name'] ?? '-') . ' ' . ($c['value'] ? '(' . $c['value'] . ')' : '')));
        if (!empty($c['description'])) $pdf->BodyText($c['description']);
        if (!empty($c['symptoms'])) $pdf->BulletList($c['symptoms']);
    }
}

// ---- CONTEXTUAL INSIGHTS ----
if (!empty($analysis['contextual_insights'])) {
    $pdf->SectionTitle('Contextual Insights');
    $pdf->BodyText($analysis['contextual_insights']);
}

// ---- RECOMMENDATIONS ----
if (!empty($analysis['recommendations']) && is_array($analysis['recommendations'])) {
    $pdf->SectionTitle('Lens & Care Recommendations');
    $pdf->BulletList($analysis['recommendations']);
}

// ---- SAVE ----
try {
    $pdf->Output('F', $output_path);
} catch (Exception $e) {
    http_response_code(500);
    echo json_encode(['error' => 'Failed to save PDF: ' . $e->getMessage()]);
    exit();
}

echo json_encode([
    'success'  => true,
    'file'     => 'pdf_file/' . $safe_filename,
    'filename' => $safe_filename
]);
