-- Generated by sync.php on 2026-07-19 05:27:44
SET FOREIGN_KEY_CHECKS=0;
SET AUTOCOMMIT=0;
START TRANSACTION;

DROP TABLE IF EXISTS `activity_log`;
CREATE TABLE `activity_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `changed_by` varchar(100) DEFAULT NULL,
  `changed_at` datetime DEFAULT NULL,
  `list` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

DROP TABLE IF EXISTS `custom_frames`;
CREATE TABLE `custom_frames` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `invoice_number` varchar(50) NOT NULL COMMENT 'Nomor invoice yang terkait',
  `brand_key` varchar(100) NOT NULL COMMENT 'Pola: dd/mm/yyyy+brand_name, contoh: 05/04/2026+brenden',
  `sell_price` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT 'Harga jual frame',
  `is_purchased` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 = belum dibeli, 1 = dibeli',
  `created_by` varchar(100) NOT NULL DEFAULT 'system',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `buy_price` decimal(12,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id`),
  KEY `idx_invoice_number` (`invoice_number`),
  KEY `idx_brand_key` (`brand_key`),
  KEY `idx_is_purchased` (`is_purchased`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Frame custom yang tidak ada di frames_main maupun frame_staging';

INSERT INTO `custom_frames` (`id`, `invoice_number`, `brand_key`, `sell_price`, `is_purchased`, `created_by`, `created_at`, `buy_price`) VALUES
('1', '002', '56-17-150+17/07+PORSCHE DESIGN', '265000.00', '1', 'LenZa786', '2026-07-17 18:55:48', '62000.00'),
('2', '003', '147-20-145+17/07+LENZA', '160000.00', '1', 'LenZa786', '2026-07-17 19:00:16', '36000.00'),
('3', '007', '49-19-142+17/07+Z-GENEREATION', '257000.00', '1', 'LenZa786', '2026-07-17 19:29:57', '62000.00'),
('4', '008', '53-15-151+17/07+XINSHISHANG', '90000.00', '1', 'LenZa786', '2026-07-17 19:36:17', '20000.00'),
('5', '010', '50-21-150+17/07+CANDICE', '90000.00', '1', 'LenZa786', '2026-07-17 19:41:46', '20000.00'),
('6', '011', '43-17-131+17/07+MILENIAL', '130000.00', '1', 'LenZa786', '2026-07-17 19:46:11', '30000.00'),
('7', '012', '57-18-146+18/07+LENZA', '160000.00', '1', 'LenZa786', '2026-07-18 10:16:44', '36000.00'),
('8', '013', '50-17-140+18/07+LENZA', '90000.00', '1', 'LenZa786', '2026-07-18 11:33:05', '20000.00');

DROP TABLE IF EXISTS `customer_examinations`;
CREATE TABLE `customer_examinations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `examination_date` date NOT NULL,
  `examination_code` varchar(25) NOT NULL,
  `customer_name` varchar(100) NOT NULL,
  `gender` enum('MALE','FEMALE') NOT NULL,
  `age` int(11) DEFAULT NULL,
  `symptoms` text DEFAULT NULL,
  `old_r_sph` varchar(5) DEFAULT NULL,
  `old_r_cyl` varchar(5) DEFAULT NULL,
  `old_r_ax` varchar(3) DEFAULT NULL,
  `old_r_add` varchar(5) DEFAULT NULL,
  `old_l_sph` varchar(5) DEFAULT NULL,
  `old_l_cyl` varchar(5) DEFAULT NULL,
  `old_l_ax` varchar(3) DEFAULT NULL,
  `old_l_add` varchar(5) DEFAULT NULL,
  `new_r_sph` varchar(5) DEFAULT NULL,
  `new_r_cyl` varchar(5) DEFAULT NULL,
  `new_r_ax` varchar(3) DEFAULT NULL,
  `new_r_add` varchar(5) DEFAULT NULL,
  `new_r_visus` varchar(6) DEFAULT NULL,
  `new_l_sph` varchar(5) DEFAULT NULL,
  `new_l_cyl` varchar(5) DEFAULT NULL,
  `new_l_ax` varchar(3) DEFAULT NULL,
  `new_l_add` varchar(5) DEFAULT NULL,
  `new_l_visus` varchar(6) DEFAULT NULL,
  `pd_dist` varchar(10) DEFAULT '62/60',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `invoice_number` varchar(20) DEFAULT '00',
  `exam_notes` text DEFAULT NULL,
  `visual_habit` tinyint(1) DEFAULT 1 COMMENT '1:Indoor, 2:Outdoor, 3:Both',
  `digital_usage` tinyint(1) DEFAULT 1 COMMENT '1:Low, 2:Moderate, 3:High',
  `ucva_r` varchar(10) DEFAULT '20/20',
  `ucva_l` varchar(10) DEFAULT '20/20',
  `lens_modification` tinyint(1) DEFAULT 0,
  `need_distance` tinyint(1) NOT NULL DEFAULT 0 COMMENT '1=Yes, 0=No — Kebutuhan jarak jauh',
  `need_intermediate` tinyint(1) NOT NULL DEFAULT 0 COMMENT '1=Yes, 0=No — Kebutuhan jarak menengah',
  `need_near` tinyint(1) NOT NULL DEFAULT 0 COMMENT '1=Yes, 0=No — Kebutuhan jarak dekat',
  `created_by` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `examination_code` (`examination_code`),
  KEY `invoice_number` (`invoice_number`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

INSERT INTO `customer_examinations` (`id`, `examination_date`, `examination_code`, `customer_name`, `gender`, `age`, `symptoms`, `old_r_sph`, `old_r_cyl`, `old_r_ax`, `old_r_add`, `old_l_sph`, `old_l_cyl`, `old_l_ax`, `old_l_add`, `new_r_sph`, `new_r_cyl`, `new_r_ax`, `new_r_add`, `new_r_visus`, `new_l_sph`, `new_l_cyl`, `new_l_ax`, `new_l_add`, `new_l_visus`, `pd_dist`, `created_at`, `invoice_number`, `exam_notes`, `visual_habit`, `digital_usage`, `ucva_r`, `ucva_l`, `lens_modification`, `need_distance`, `need_intermediate`, `need_near`, `created_by`) VALUES
('1', '2025-07-21', 'LZ/EC/001/VII/2025', 'UNKNOWN', 'FEMALE', '63', 'MYOPIA, HYPEROPIA, ASTIGMATISM, PRESBYOPIA, CATARACT, HYPERTENSION (145, CONTROLLED), OTHERS: MATA KANAN YANG CATARACT', '0.00', '0.00', '0', '0.00', '0.00', '0.00', '0', '0.00', '-25', '-50', '70', '+3.00', '20/20', '+50', '0.00', '0', '+3.00', '20/20', '62/60', '2026-07-17 18:49:36', '00', 'BELUM BELI', '1', '1', '20/30', '20/25', '0', '1', '0', '1', 'LenZa786'),
('2', '2025-07-21', 'LZ/EC/002/VII/2025', 'PUTRI', 'FEMALE', '28', 'MYOPIA', '0.00', '0.00', '0', '0.00', '0.00', '0.00', '0', '0.00', '-50', '0.00', '0', '0.00', '20/20', '-50', '0.00', '0', '0.00', '20/20', '64', '2026-07-17 18:51:17', '001', '', '3', '2', '20/30', '20/30', '0', '0', '0', '0', 'LenZa786'),
('3', '2025-07-22', 'LZ/EC/003/VII/2025', 'MUHAMMAD RAIS LATIF', 'MALE', '29', 'MYOPIA, ASTIGMATISM, HEADACHE, EYE STRAIN', '0.00', '-0.50', '10', '0.00', '0.00', '-0.75', '10', '0.00', '-25', '-25', '10', '0.00', '20/20', '0.00', '-50', '15', '0.00', '20/20', '60', '2026-07-17 18:54:59', '002', '', '3', '3', '20/25', '20/25', '0', '0', '0', '0', 'LenZa786'),
('4', '2025-07-22', 'LZ/EC/004/VII/2025', 'SILVA', 'FEMALE', '22', 'MYOPIA, ASTIGMATISM, HEADACHE, OTHERS: KACAMATA LAMA JIKA DIGUNAKAN LAMA TERASA TIDAK NYAMAN', '-125', '0.00', '0', '0.00', '-175', '0.00', '0', '0.00', '-75', '-50', '30', '0.00', '20/20', '-150', '0.00', '0', '0.00', '20/20', '62', '2026-07-17 18:59:37', '003', '', '3', '2', '20/50', '20/80', '0', '0', '0', '0', 'LenZa786'),
('5', '2025-07-24', 'LZ/EC/000-004/VII/2025', 'VENI', 'FEMALE', '0', 'DIRECT SALE', '0.00', '0.00', '0', '0.00', '0.00', '0.00', '0', '0.00', '-125', '0.00', '0', '0.00', '20/20', '-125', '0.00', '0', '0.00', '20/20', '62', '2026-07-17 19:03:17', '004', 'DISPENSING ONLY', '3', '2', '20/20', '20/20', '0', '0', '0', '0', 'LenZa786'),
('6', '2025-07-26', 'LZ/EC/005/VII/2025', 'AGUS', 'FEMALE', '60', 'HYPEROPIA, PRESBYOPIA', '0', '0.00', '0', '+175', '+50', '0.00', '0', '+175', '+50', '0.00', '0', '+300', '20/20', '+50', '0.00', '0', '+300', '20/20', '62/60', '2026-07-17 19:10:29', '005', '', '1', '1', '20/25', '20/25', '0', '1', '0', '1', 'LenZa786'),
('7', '2025-07-27', 'LZ/EC/006/VII/2025', 'ROSNI', 'FEMALE', '59', 'MYOPIA, ASTIGMATISM, PRESBYOPIA, CATARACT, OTHERS: SUDAH OPERASI, NAMUN TIDAK TERKONTROL', '+125', '0.00', '0', '+250', '+175', '0.00', '0', '+250', '-100', '-50', '130', '+2.75', '20/20', '-25', '-50', '165', '+2.75', '20/20', '59/57', '2026-07-17 19:14:15', '006', '', '1', '1', '20/70', '20/30', '0', '1', '0', '1', 'LenZa786'),
('8', '2025-07-28', 'LZ/EC/000-007/VII/2025', 'NAZRI', 'MALE', '13', 'DIRECT SALE', '0.00', '0.00', '0', '0.00', '0.00', '0.00', '0', '0.00', '+300', '0.00', '0', '0.00', '20/20', '+400', '0.00', '0', '0.00', '20/20', '60', '2026-07-17 19:27:19', '007', 'DISPENSING ONLY', '3', '3', '20/20', '20/20', '0', '0', '0', '0', 'LenZa786'),
('9', '2025-07-28', 'LZ/EC/000-008/VII/2025', 'UNKNOWN', 'MALE', '0', 'DIRECT SALE', '0.00', '0.00', '0', '0.00', '0.00', '0.00', '0', '0.00', '0.00', '0.00', '0', '0.00', '20/20', '0.00', '0.00', '0', '0.00', '20/20', '62', '2026-07-17 19:32:34', '008', 'DISPENSING ONLY', '1', '1', '20/20', '20/20', '0', '0', '0', '0', 'LenZa786'),
('10', '2025-07-31', 'LZ/EC/007/VII/2025', 'NURMAN', 'MALE', '60', 'MYOPIA, PRESBYOPIA, OTHERS: OPERASI KATARAK 2 TAHUN YANG LALU, SUKSES', '-75', '0.00', '0', '0.00', '-75', '0.00', '0', '0.00', '-50', '0.00', '0', '+300', '20/20', '-50', '0.00', '0', '+300', '20/20', '63/61', '2026-07-17 19:39:08', '009', 'LENSA KACAMATA YANG LAMA HANYA UNTUK JAUH', '1', '1', '20/20', '20/20', '0', '1', '0', '1', 'LenZa786'),
('11', '2025-07-30', 'LZ/EC/000-010/VII/2025', 'UNKNOWN', 'MALE', '0', 'DIRECT SALE', '0.00', '0.00', '0', '0.00', '0.00', '0.00', '0', '0.00', '0.00', '0.00', '0', '0.00', '20/20', '0.00', '0.00', '0', '0.00', '20/20', '62', '2026-07-17 19:41:11', '010', 'DISPENSING ONLY', '1', '1', '20/20', '20/20', '0', '0', '0', '0', 'LenZa786'),
('12', '2025-08-03', 'LZ/EC/008/VIII/2025', 'VIVI', 'FEMALE', '13', 'MYOPIA', '-125', '0.00', '0', '0.00', '-125', '0.00', '0', '0.00', '-300', '0.00', '0', '0.00', '20/20', '-300', '0.00', '0', '0.00', '20/20', '60', '2026-07-17 19:45:38', '011', '', '3', '2', '20/400', '20/400', '0', '0', '0', '0', 'LenZa786'),
('13', '2025-08-05', 'LZ/EC/000-012/VIII/2025', 'UNKNOWN', 'MALE', '0', 'DIRECT SALE', '0.00', '0.00', '0', '0.00', '0.00', '0.00', '0', '0.00', '0.00', '0.00', '0', '0.00', '20/20', '0.00', '0.00', '0', '0.00', '20/20', '62', '2026-07-18 10:15:59', '012', 'DISPENSING ONLY', '1', '1', '20/20', '20/20', '0', '0', '0', '0', 'LenZa786'),
('14', '2025-08-06', 'LZ/EC/009/VIII/2025', 'HAFID', 'MALE', '12', 'MYOPIA, ASTIGMATISM, OTHERS: ADA FAKTOR KETURUNAN', '0.00', '0.00', '0', '0.00', '0.00', '0.00', '0', '0.00', '-200', '-50', '180', '0.00', '20/20', '-200', '-50', '180', '0.00', '20/20', '60', '2026-07-18 11:32:33', '013', '', '1', '2', '20/200', '20/200', '0', '0', '0', '0', 'LenZa786'),
('15', '2025-08-07', 'LZ/EC/010/VIII/2025', 'MIRO', 'FEMALE', '50', 'HYPEROPIA, PRESBYOPIA', '0.00', '0.00', '0', '0.00', '0.00', '0.00', '0', '0.00', '+50', '0.00', '0', '+2.00', '20/20', '+50', '0.00', '0', '+2.00', '20/20', '61/59', '2026-07-18 11:43:32', '014', '', '1', '1', '20/25', '20/25', '0', '1', '0', '1', 'LenZa786');

DROP TABLE IF EXISTS `customer_orders`;
CREATE TABLE `customer_orders` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `customer_number` varchar(40) NOT NULL,
  `invoice_number` varchar(50) NOT NULL,
  `is_modified` tinyint(1) NOT NULL DEFAULT 0,
  `frame_ufc` varchar(50) DEFAULT NULL,
  `lens_name` varchar(150) DEFAULT NULL,
  `customer_phone` varchar(30) DEFAULT NULL,
  `customer_address` text DEFAULT NULL,
  `total_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `amount_paid` decimal(15,2) NOT NULL DEFAULT 0.00,
  `order_date` date NOT NULL,
  `due_date` date DEFAULT NULL,
  `order_status` int(11) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `packaging_cost` int(11) NOT NULL DEFAULT 19500,
  `created_by` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_customer_number` (`customer_number`),
  UNIQUE KEY `uq_invoice_number` (`invoice_number`),
  KEY `idx_order_status` (`order_status`),
  KEY `idx_order_date` (`order_date`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Confirmed purchase orders — saved when operator clicks Yes Shopping';

INSERT INTO `customer_orders` (`id`, `customer_number`, `invoice_number`, `is_modified`, `frame_ufc`, `lens_name`, `customer_phone`, `customer_address`, `total_amount`, `amount_paid`, `order_date`, `due_date`, `order_status`, `created_at`, `updated_at`, `packaging_cost`, `created_by`) VALUES
('1', '1/LZ-C/15.13/002/VII/25', '001', '0', NULL, 'SINGLE VISION — PHOTOCHROMIC', '+62 895 0913 7239', 'JL. DELIMA I NO. 181', '150000.00', '0.00', '2025-07-21', '2025-07-23', '5', '2026-07-17 18:52:20', '2026-07-17 19:01:35', '19500', 'LenZa786'),
('2', '2/LZ-C/15.14/003/VII/25', '002', '0', NULL, 'SINGLE VISION — HMC', '+62 812 6764 6916', 'JL. APEL RAYA NO. 51', '0.00', '0.00', '2025-07-22', '2025-07-24', '5', '2026-07-17 18:56:34', '2026-07-17 19:01:32', '19500', 'LenZa786'),
('3', '3/LZ-C/15.15/004/VII/25', '003', '0', NULL, 'SINGLE VISION — BLUERAY', '+62 896 5499 5927', 'KURANJI', '230000.00', '230000.00', '2025-07-22', '2025-07-24', '5', '2026-07-17 19:01:08', '2026-07-17 19:01:27', '19500', 'LenZa786'),
('4', '4/LZ-C/15.16/000/VII/25', '004', '0', NULL, 'SINGLE VISION — HMC', '+62 813 7823 3630', 'JL. TADUAH PERUMAHAN NURUL HASANAH', '90000.00', '90000.00', '2025-07-24', '2025-07-26', '5', '2026-07-17 19:04:09', '2026-07-17 19:07:08', '19500', 'LenZa786'),
('5', '5/LZ-C/15.17/005/VII/25', '005', '0', NULL, 'PROGRESSIVE — HMC', '+62 812 6675 5007', 'JL. APEL RAYA NO. 73', '160000.00', '100000.00', '2025-07-26', '2025-07-28', '5', '2026-07-17 19:11:13', '2026-07-17 19:15:16', '19500', 'LenZa786'),
('6', '6/LZ-C/15.18/006/VII/25', '006', '0', NULL, 'KRYPTOK — HMC', '+62 821 7040 9712', 'DURIAN 3 BATANG, KORONG GADANG', '285000.00', '100000.00', '2025-07-27', '2025-08-06', '5', '2026-07-17 19:14:58', '2026-07-17 19:15:12', '19500', 'LenZa786'),
('7', '7/LZ-C/15.19/000/VII/25', '007', '0', NULL, 'SINGLE VISION — BLUERAY', '+62 812 6781 895', 'RINDANG ALAM', '300000.00', '0.00', '2025-07-28', '2025-07-30', '5', '2026-07-17 19:30:41', '2026-07-17 19:31:09', '19500', 'LenZa786'),
('8', '8/LZ-C/15.20/000/VII/25', '008', '0', NULL, NULL, '+62 8', NULL, '90000.00', '90000.00', '2025-07-28', '2025-07-30', '5', '2026-07-17 19:36:33', '2026-07-17 19:36:49', '19500', 'LenZa786'),
('9', '9/LZ-C/15.21/007/VII/25', '009', '0', NULL, 'PROGRESSIVE — ANTI-BLUE RAY', '+62 853 5692 1505', 'JL. RAMBUTAN XII NO.192', '220000.00', '100000.00', '2025-07-31', '2025-08-02', '5', '2026-07-17 19:40:12', '2026-07-17 19:47:33', '19500', 'LenZa786'),
('10', '10/LZ-C/15.22/000/VII/25', '010', '0', NULL, NULL, '+62 8', NULL, '90000.00', '90000.00', '2025-07-30', '2025-08-01', '5', '2026-07-17 19:42:05', '2026-07-17 19:47:37', '19500', 'LenZa786'),
('11', '11/LZ-C/15.23/008/VIII/25', '011', '0', NULL, 'SINGLE VISION — BLUGARD (STOCK)', '+62 813 7456 1556', 'INTAN SARI INDAH BLOK B XI', '400000.00', '100000.00', '2025-08-03', '2025-08-13', '5', '2026-07-17 19:47:15', '2026-07-17 19:47:29', '19500', 'LenZa786'),
('12', '12/LZ-C/15.24/000/VIII/25', '012', '0', NULL, NULL, '+62 8', NULL, '140000.00', '0.00', '2025-08-05', '2025-08-07', '5', '2026-07-18 10:17:10', '2026-07-18 10:17:22', '19500', 'LenZa786'),
('13', '13/LZ-C/15.25/009/VIII/25', '013', '0', NULL, 'SINGLE VISION — HMC', '+62 852 6371 5017', 'JL. JERUK VIII', '180000.00', '100000.00', '2025-08-06', '2025-08-08', '5', '2026-07-18 11:33:58', '2026-07-18 11:34:10', '19500', 'LenZa786'),
('14', '14/LZ-C/15.26/010/VIII/25', '014', '0', NULL, 'PROGRESSIVE — PHOTOCHROMIC', '+62 852 6343 0923', 'JL. SIRSAK VII', '220000.00', '120000.00', '2025-08-07', '2025-08-09', '5', '2026-07-18 11:44:27', '2026-07-18 11:44:38', '19500', 'LenZa786');

DROP TABLE IF EXISTS `deleted_records`;
CREATE TABLE `deleted_records` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `table_name` varchar(100) NOT NULL,
  `record_id` varchar(255) NOT NULL,
  `deleted_by` varchar(100) NOT NULL,
  `deleted_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `synced` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_deleted` (`table_name`,`record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

DROP TABLE IF EXISTS `frame_staging`;
CREATE TABLE `frame_staging` (
  `ufc` varchar(100) NOT NULL,
  `brand` varchar(50) NOT NULL,
  `frame_code` varchar(50) DEFAULT 'lz-786',
  `frame_size` varchar(50) DEFAULT '00-00-786',
  `color_code` varchar(50) DEFAULT NULL,
  `material` varchar(50) DEFAULT NULL,
  `lens_shape` varchar(50) DEFAULT NULL,
  `structure` enum('full-rim','semi-rimless','rimless') DEFAULT NULL,
  `size_range` enum('small','medium','large') DEFAULT NULL,
  `gender_category` enum('men','female','unisex') NOT NULL DEFAULT 'unisex',
  `buy_price` decimal(15,2) DEFAULT 0.00,
  `sell_price` decimal(15,2) DEFAULT 0.00,
  `price_secret_code` varchar(20) DEFAULT NULL,
  `stock` int(11) DEFAULT 1,
  `stock_age` enum('very old','old','new') DEFAULT 'new',
  `created_by` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ufc`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

DROP TABLE IF EXISTS `frames_main`;
CREATE TABLE `frames_main` (
  `ufc` varchar(100) NOT NULL,
  `brand` varchar(50) DEFAULT NULL,
  `frame_code` varchar(50) DEFAULT NULL,
  `frame_size` varchar(50) DEFAULT NULL,
  `color_code` varchar(50) DEFAULT NULL,
  `material` varchar(50) DEFAULT NULL,
  `lens_shape` varchar(50) DEFAULT NULL,
  `structure` enum('full-rim','semi-rimless','rimless') DEFAULT NULL,
  `size_range` enum('small','medium','large') DEFAULT NULL,
  `gender_category` enum('men','female','unisex') NOT NULL DEFAULT 'unisex',
  `buy_price` decimal(15,2) DEFAULT NULL,
  `sell_price` decimal(15,2) DEFAULT NULL,
  `price_secret_code` varchar(20) DEFAULT NULL,
  `stock` int(11) DEFAULT 0,
  `stock_age` enum('very old','old','new') DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`ufc`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

DROP TABLE IF EXISTS `prescription_modifications`;
CREATE TABLE `prescription_modifications` (
  `modification_id` int(11) NOT NULL AUTO_INCREMENT,
  `invoice_number` varchar(20) NOT NULL,
  `od_sph` varchar(10) DEFAULT NULL,
  `od_cyl` varchar(10) DEFAULT NULL,
  `od_axis` varchar(10) DEFAULT NULL,
  `od_add` varchar(10) DEFAULT NULL,
  `os_sph` varchar(10) DEFAULT NULL,
  `os_cyl` varchar(10) DEFAULT NULL,
  `os_axis` varchar(10) DEFAULT NULL,
  `os_add` varchar(10) DEFAULT NULL,
  `modified_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`modification_id`),
  KEY `fk_invoice_mod` (`invoice_number`),
  CONSTRAINT `fk_invoice_mod` FOREIGN KEY (`invoice_number`) REFERENCES `customer_examinations` (`invoice_number`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

DROP TABLE IF EXISTS `settings`;
CREATE TABLE `settings` (
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

INSERT INTO `settings` (`setting_key`, `setting_value`, `description`) VALUES
('backup_location', '/backup/', 'Server Path for Backup File Storage'),
('barcode_guide_image_location', 'image/barcode_guide_1777292613.png', 'Path to the comprehensive guide barcode image file.'),
('brand_image_location', 'image/brand_logo_1769435885.png', 'File path or URL for the company brand logo image.'),
('copyright_footer', '© 2026 LENZA OPTIC. All rights reserved.', 'The copyright message displayed in the footer of all application pages.'),
('db_backup_blocking_time', '20:30', 'Time of day after which database backup is blocked. Changing this requires the Main Admin password.'),
('invoice_format_prefix', '[data_sequence]/LO-C/[invoice_number]/[test_result_table_number]/[month]/[year]', 'Prefix for Invoice Numbering (e.g., INV-2026-...)'),
('last_backup_date', '2026-01-01', 'Date of the Last System Backup (Auto-updated)'),
('lens_lab_lead_time_days', '10', 'Default estimated waiting time (in days) for lab-order lens orders'),
('lens_stock_lead_time_days', '2', 'Default estimated waiting time (in days) for stock lens orders'),
('main_admin_shortcut_password', '8643262924', 'Plaintext copy of the Main Admin password. Update manually whenever the real password changes.'),
('main_admin_shortcut_password_init', '1', 'Triggers password shortcut translation.'),
('main_admin_shortcut_username', 'LenZa786', 'The real Main Admin username that the shortcut translates to.'),
('main_admin_shortcut_username_init', '1', 'Triggers username shortcut translation.'),
('main_admin_username', 'LenZa786', 'Username of the user designated as Main Admin. Changing this value requires the current Main Admin login password.'),
('starting_invoice_number', '15.13', 'The starting sequence/text string for invoice numbering (resets automatically).'),
('store_address', 'Jl. Apel Raya, No. 50, Kuranji, Padang, Sumatera Barat, 25157, Indonesia', 'Store Physical Address'),
('store_name', 'LENZA OPTIC', 'Store Name for Receipts and Reports'),
('store_phone', '+62 812 6764 6916', 'Store Contact Phone Number');

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `role` enum('admin','staff','viewer') NOT NULL,
  `is_approved` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `last_login` timestamp NULL DEFAULT NULL,
  `session_token` varchar(64) DEFAULT NULL,
  `session_expires` datetime DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

INSERT INTO `users` (`user_id`, `username`, `password_hash`, `role`, `is_approved`, `created_at`, `last_login`, `session_token`, `session_expires`) VALUES
('1', 'LenZa786', '$2y$10$E5ZXU41IpXcB443wtKCIou/cpEaFMa7k2tuOx83ZAQ9soeUPagGWm', 'admin', '1', '2026-01-12 12:15:58', '2026-07-19 05:26:00', NULL, NULL),
('17', 'rais786', '$2y$10$Nvp2WWM.r5i1uM7VQD9t8eTZzeGNtDEz.A0NhEdUjPGzeZ8z7bFeO', 'staff', '0', '2026-05-28 20:17:44', '2026-06-08 14:27:52', NULL, NULL);

COMMIT;
SET FOREIGN_KEY_CHECKS=1;
